name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          libgtest-dev \
          libgmock-dev \
          googletest \
          google-mock

    - name: Build and install GTest/GMock
      run: |
        # Build and install GTest
        cd /usr/src/googletest
        sudo cmake CMakeLists.txt
        sudo make
        sudo make install
        
        # Build and install GMock
        cd /usr/src/gmock
        sudo cmake CMakeLists.txt
        sudo make
        sudo make install

    - name: Configure and build
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        cmake --build . --config Release --parallel 2
        ctest --output-on-failure

    - name: Create DEB package
      run: |
        mkdir -p package/usr/bin
        cp build/BusinessMediatorDemo package/usr/bin/
        find build/test -maxdepth 1 -type f -executable -exec cp {} package/usr/bin/ \;
        
        mkdir -p package/DEBIAN
        cat <<EOF > package/DEBIAN/control
        Package: business-mediator
        Version: 1.0-$(date +%Y%m%d%H%M%S)
        Section: base
        Priority: optional
        Architecture: amd64
        Maintainer: netrivialnogo <kbelovwowcirkle@gmail.com>
        Description: Business Mediator Pattern Implementation
        EOF
        
        dpkg-deb --build package business-mediator.deb

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: business-mediator-package
        path: build/business-mediator.deb
